POST http://127.0.0.1:4000/jam/create
Content-Type: application/json

{
  "public": false
}

###

GET http://127.0.0.1:4000/jam/list

###

POST http://127.0.0.1:4000/jam/edit
Authorization: UTECZFAL VFN4xZh6PCYGuOmI8jbx
Content-Type: application/json

{
  "name": "bagel"
}

###